version: "3.5"
services:
  redis:
    container_name: cache
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis-data:/var/lib/redis
      - ./volumes/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
